require("user.plugins.autopairs")
require("user.options")
require("user.keymaps")
require("user.plugins.plugins")
require("user.plugins.treesitter")
require("user.plugins.lualine")
require("user.plugins.nvim-tree")
-- require("user.plugins.colorscheme")
require("user.plugins.kanagawa")
require("user.plugins.vim-tmux-runner")
require("user.plugins.cmp")
require("user.plugins.lsp")
-- require('user.toggleterm')
require("user.autocmds")
require("user.functions")
require("user.plugins.luasnip")
