require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.treesitter')
require('user.lualine')
require('user.nvim-tree')
require('user.colorscheme')
require('user.vim-tmux-runner')
require('user.cmp')
require('user.lsp')
-- require('user.toggleterm')
require("user.autocmds")
require("user.functions")
require("user.snip")
